name: Build static library

on:
  workflow_dispatch:

jobs:
  build:
    name: Build lol_html crate
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - build: linux-x86_64
            os: ubuntu-latest
          - build: macos-x86_64
            os: macos-latest
          - build: windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-gnu
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "cloudflare/lol-html"

      - name: Configure Cargo target
        run: |
          echo CARGO_BUILD_TARGET=${{ matrix.target }} >> $GITHUB_ENV
          rustup target add ${{ matrix.target }}
        if: matrix.target != ''

      - run: cargo build --lib --release --manifest-path c-api/Cargo.toml
        if: matrix.os != 'windows-latest'
      - run: cargo build --lib --release --target ${{ matrix.target }} --manifest-path c-api/Cargo.toml
        if: matrix.os == 'windows-latest'
      
      - run: mkdir dist

      - run: cp c-api/target/release/liblolhtml.a dist
        if: matrix.os != 'windows-latest'
      - run: cp c-api/target/${{ matrix.target }}/release/liblolhtml.a dist
        if: matrix.build == 'windows-x86_64'

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.build }}
          path: dist

      - uses: actions/upload-artifact@v2
        with:
          name: include
          path: c-api/include
        if: matrix.os == 'ubuntu-latest'
